# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('groups_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Groups')),
            ],
            options={
                'db_table': 'catalog',
            },
        ),
    ]
