# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-29 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_manufacturer', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'manufacturer',
            },
        ),
        migrations.AlterField(
            model_name='catalog',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Manufacturer'),
        ),
    ]
