# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-12 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_provider_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='groups_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Groups', verbose_name='Группа товара'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name_product',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='groups_products',
            field=models.CharField(max_length=200, verbose_name='Группа товара'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(max_length=64, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name_manufacturer',
            field=models.CharField(max_length=200, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name_provider',
            field=models.CharField(max_length=200, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='number_street',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='street',
            field=models.CharField(max_length=64, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='date_of_supply',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='products',
            field=models.CharField(max_length=200, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
